# Prometheus configuration for monitoring the EV Analysis platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files specify a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - "alert_rules.yml"

# A scrape configuration for running Prometheus on a Kubernetes cluster.
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the FastAPI backend
  - job_name: 'ev-analysis-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scrape PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Scrape Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Scrape Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Scrape MLflow metrics if available
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for custom metrics
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Custom recording rules for ML metrics
- name: ml_metrics
  rules:
    # Model accuracy over time
    - record: ml:model_accuracy:rate5m
      expr: rate(model_accuracy_total[5m])
    
    # Prediction request rate
    - record: ml:prediction_requests:rate1m
      expr: rate(prediction_requests_total[1m])
    
    # Model training duration
    - record: ml:training_duration:avg
      expr: avg(model_training_duration_seconds)

# Alert rules
- name: application_alerts
  rules:
    # High error rate alert
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 10% for the last 5 minutes"

    # High response time alert
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1.0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 1 second"

    # Database connection issues
    - alert: DatabaseDown
      expr: up{job="postgres"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Database is down"
        description: "PostgreSQL database is not responding"

    # Redis connection issues  
    - alert: RedisDown
      expr: up{job="redis"} == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Redis is down"
        description: "Redis cache is not responding"

    # Low model accuracy
    - alert: LowModelAccuracy
      expr: ml:model_accuracy:rate5m < 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Model accuracy degraded"
        description: "Model accuracy has dropped below 80%"

    # High memory usage
    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High memory usage"
        description: "Memory usage is above 90%"

    # High CPU usage
    - alert: HighCPUUsage
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is above 90%"

    # Disk space running low
    - alert: DiskSpaceLow
      expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Disk space running low"
        description: "Available disk space is below 10%"